start /wait cmd /c npm run build qbm
start /wait cmd /c npm run build qer
start /wait cmd /c npm run build:dynamic tsb
start /wait cmd /c npm run build:dynamic att
start /wait cmd /c npm run build:dynamic rms
start /wait cmd /c npm run build:dynamic aad
start /wait cmd /c npm run build:dynamic aob
start /wait cmd /c npm run build:dynamic uci
start /wait cmd /c npm run build:dynamic cpl
start /wait cmd /c npm run build:dynamic dpr
start /wait cmd /c npm run build:dynamic rmb
start /wait cmd /c npm run build:dynamic rps
start /wait cmd /c npm run build:dynamic o3t
start /wait cmd /c npm run build:dynamic olg
start /wait cmd /c npm run build:dynamic hds
start /wait cmd /c npm run build:dynamic pol
start /wait cmd /c npm run build:dynamic apc
start /wait cmd /c npm run build:dynamic sac
start /wait cmd /c npm run build:app qer-app-portal
start /wait cmd /c npm run build:app qbm-app-landingpage
::start /wait cmd /c npm run build:app qer-app-operationssupport
::start /wait cmd /c npm run build:app qer-app-pwdportal
::start /wait cmd /c npm run build:app custom-app
